version: '3'
services:
  glpi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GLPI_DB_USER=glpi
      - GLPI_DB_PASSWORD=glpi
      - GLPI_DB_NAME=glpi
      - GLPI_DB_HOST=glpi-db
    volumes:
      - /glpi:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
    links:
      - glpi-db
  glpi-db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
    volumes:
      - glpi-db-data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  glpi-db-data:
